name: Lint

on:
  push:
    branches-ignore: []  # Run on all branches
  pull_request:
    branches-ignore: []  # Run on all branches

jobs:
  lint:
    runs-on: ubuntu-22.04  # More lightweight than ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install dependencies
        run: |
          pnpm add -D next@15.2.4 react@^18.3.1 react-dom@^18.3.1
          pnpm add -D eslint
          pnpm install --frozen-lockfile=false
        
      - name: Run ESLint
        run: pnpm run lint 